#ifndef TFTP_COMMON_VALUES_H_INCLUDED
#define TFTP_COMMON_VALUES_H_INCLUDED

#define TFTP_FILENAME_MAX   (127)
#define TFTP_TIMEOUT_MS     (1000)
#define TFTP_RETRIES        (3)

#endif // TFTP_COMMON_VALUES_H_INCLUDED
